FROM grafana/grafana:6.0.2
MAINTAINER livenowhy <livenowhy@hotmail.com>

COPY ./aliyun-cms-grafana  /var/lib/grafana/plugins/aliyun-cms-grafana

#

# cd /var/lib/grafana/plugins/
# git clone https://github.com/aliyun/aliyun-cms-grafana.git
# registry.cn-zhangjiakou.aliyuncs.com/livenowhy/grafana:6.0.2