FROM registry.cn-zhangjiakou.aliyuncs.com/livenowhy/alertmanager:v0.15.3
MAINTAINER livenowhy <livenowhy@hotmail.com>
COPY alertmanager.yml   /etc/alertmanager/alertmanager.yml
COPY template           /etc/alertmanager/template

# docker run --name alertmanager -d -p 9093:9093   registry.cn-zhangjiakou.aliyuncs.com/livenowhy/alertmanager:lastest