version: '3.3'
services:
  # 0、node_exporter 通过 node_exporter 采集数据

  # 1、prometheus 服务
  # a. prometheus.yml 配置文件 (用了配置数据源)
  # b. rules.yml      配置报警规则
  prometheus:
    image: registry.cn-zhangjiakou.aliyuncs.com/livenowhy/prometheus:lastest
    container_name: prometheus
    network_mode: "bridge"
    ports:
      - 9090:9090
    volumes:
      - /share/notebook/automate/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - /share/notebook/automate/prometheus/config/rules.yml:/etc/prometheus/rules.yml
    extra_hosts:
      api.livenowhy.com: 10.2.56.162
      node_exporter.livenowhy.com: 10.2.56.162
      alertmanager.livenowhy.com: 10.2.56.162
      influxdb.livenowhy.com: 10.2.56.162
      corevm.livenowhy.com: 10.2.56.162
      remote_storage_adapter.livenowhy.com: 10.2.56.162
    depends_on:
      - remote_storage_adapter
      - influxdb

  grafana:
    image:  registry.cn-zhangjiakou.aliyuncs.com/livenowhy/grafana:6.0.2
    container_name: grafana
    network_mode: "bridge"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
      - 3000:3000
    extra_hosts:
      prometheus.livenowhy.com: 10.2.56.162

  alertmanager:
    image: registry.cn-zhangjiakou.aliyuncs.com/livenowhy/alertmanager:lastest
    container_name: alertmanager
    network_mode: "bridge"
    ports:
      - 9093:9093
    volumes:
      - /share/notebook/automate/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    extra_hosts:
      prometheus.livenowhy.com: 10.2.56.162
      node_exporter.livenowhy.com: 10.2.56.162
      api.livenowhy.com: 10.2.56.162

  influxdb:
    image: registry.cn-zhangjiakou.aliyuncs.com/livenowhy/influxdb:1.8
    container_name: influxdb
    network_mode: "bridge"
    ports:
      - 8086:8086
      - 2003:2003
    environment:
      INFLUXDB_DB: prometheus

  remote_storage_adapter:
    image: registry.cn-zhangjiakou.aliyuncs.com/livenowhy/remote_storage_adapter:lastest
    container_name: remote_storage_adapter
    network_mode: "bridge"
    entrypoint:
      - /bin/remote_storage_adapter
      - --influxdb-url=http://10.2.56.162:8086  # influxdb 的地址,使用域名存在问题
      - --influxdb.database=prometheus
      - --influxdb.retention-policy=autogen
    ports:
      - 9201:9201
    depends_on:
      - influxdb
  # ./remote_storage_adapter --influxdb-url=http://10.2.56.162:8086 --influxdb.database=prometheus --influxdb.retention-policy=autogen
  # 9201 端口是 remote_storage_adapter 默认监听的端口

# docker-compose stop & docker-compose rm -f
# docker-compose up -d
# docker ps -a --no-trunc
# 10.2.56.162 本机ip 本地执行 node_exporter 启动 node_exporter
# docker run -d -p 9090:9090 --name prometheus  registry.cn-zhangjiakou.aliyuncs.com/livenowhy/prometheus:2.22.0
