version: '3.3'
services:
  mysql_01:
    image: registry.cn-zhangjiakou.aliyuncs.com/livenowhy/mysql:5.6
    container_name: db_mysql_01
    network_mode: "bridge"
    ports:
      - 3307:3306
    volumes:
      - /dbdata/mysql/01/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "myops8639"
      MYSQL_DATABASE: cmdb

  mysql_02:
    image: registry.cn-zhangjiakou.aliyuncs.com/livenowhy/mysql:5.6
    container_name: db_mysql_02
    network_mode: "bridge"
    ports:
      - 3308:3306
    volumes:
      - /dbdata/mysql/02/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "myops12345"
      MYSQL_DATABASE: cmdb

  redis:
    image: registry.cn-zhangjiakou.aliyuncs.com/livenowhy/redis:6.0.base
    container_name: db_redis
    network_mode: "bridge"
    ports:
      - 6379:6379

  rabbitmq:
    hostname: rabbitmq
    image: registry.cn-zhangjiakou.aliyuncs.com/livenowhy/rabbitmq:3.8-management
    container_name: rabbitmq
    network_mode: "bridge"
    ports:
      - 15672:15672
      - 4369:4369
      - 5672:5672
      - 25672:25672
      - 5671:5671
    volumes:
      - /dbdata/rabbitmq:/var/lib/rabbitmq

# mkdir -p /dbdata/mysql/01/data
# mkdir -p /dbdata/mysql/02/data
# mkdir -p /dbdata/rabbitmq
# chmod -R a+wr /dbdata/mysql
# chmod -R a+wr /dbdata/rabbitmq