FROM nginx:1.18

MAINTAINER livenowhy livenowhy@hotmail.com

ADD livenowhy.conf /etc/nginx/conf.d/livenowhy.conf
ADD app.conf /etc/nginx/conf.d/app.conf
ADD sp.conf /etc/nginx/conf.d/sp.conf
ADD idp.conf /etc/nginx/conf.d/idp.conf