FROM prom/pushgateway:v1.3.0
MAINTAINER livenowhy <livenowhy@hotmail.com>

# registry.cn-zhangjiakou.aliyuncs.com/livenowhy/prometheus:2.22.0
# docker run -d -p 9090:9090 --name prometheus  registry.cn-zhangjiakou.aliyuncs.com/livenowhy/prometheus:2.22.0