version: '3.3'
services:
  rabbitmq:
    hostname: rabbitmq
    image: registry.cn-zhangjiakou.aliyuncs.com/livenowhy/rabbitmq:3.8-management
    container_name: rabbitmq
    network_mode: "bridge"
    ports:
      - 15672:15672
      - 4369:4369
      - 5672:5672
      - 25672:25672
      - 5671:5671
#    environment:
#      RABBITMQ_DEFAULT_PASS: "myops8639"
#      RABBITMQ_DEFAULT_USER: cmdb