FROM prom/node-exporter
MAINTAINER livenowhy <livenowhy@hotmail.com>

# registry.cn-zhangjiakou.aliyuncs.com/livenowhy/node_exporter:latest
# docker run -d -p 9100:9100   -v "/:/host:ro,rslave" registry.cn-zhangjiakou.aliyuncs.com/livenowhy/node_exporter:latest --path.rootfs /host

# 由于用于主机监控, 不建议部署在 docker 中


