FROM suryastef/remote_storage_adapter
MAINTAINER livenowhy <livenowhy@hotmail.com>

#CMD ["/bin/remote_storage_adapter", "--influxdb-url=http://influxdb.livenowhy.com", "--influxdb.database=prometheus", "--influxdb.retention-policy=autogen"]

# --influxdb-url=http://influxdb.livenowhy.com --influxdb.database=prometheus --influxdb.retention-policy=autogen"]

# docker run -d registry.cn-zhangjiakou.aliyuncs.com/livenowhy/remote_storage_adapter:lastest
# docker run -it registry.cn-zhangjiakou.aliyuncs.com/livenowhy/remote_storage_adapter:lastest sh

# remote_storage_adapter --influxdb-url=influxdb.livenowhy.com --influxdb.database="prometheus" --influxdb.retention-policy=autogen