version: '3.3'
services:
  mysql:
    image: registry.cn-zhangjiakou.aliyuncs.com/livenowhy/mysql:8.0
    container_name: db_mysql
    network_mode: "bridge"
    ports:
      - 3306:3306
    volumes:
      - /dbdata/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: phoenix
#      MYSQL_USER: root
#      MYSQL_PASSWORD: "123456"